# Generated by Django 6.0.6 on 2026-06-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('image_path', models.CharField(max_length=100, verbose_name='Шлях до зображення')),
            ],
            options={
                'verbose_name': 'День тижня',
                'verbose_name_plural': 'Дні тижня',
            },
        ),
    ]
