# Generated by Django 6.0.6 on 2026-06-09 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Повне ім'я")),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Ідентифікатор')),
                ('bio', models.TextField(blank=True, verbose_name='Біографія')),
            ],
            options={
                'verbose_name': 'Письменник',
                'verbose_name_plural': 'Письменники',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Ідентифікатор')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('publication_year', models.PositiveIntegerField(verbose_name='Рік видання')),
                ('top_place', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Місце в топі')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='main.writer', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['top_place'],
            },
        ),
    ]
