# Generated by Django 6.0.6 on 2026-06-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ПІБ')),
                ('city', models.CharField(max_length=50, verbose_name='Місто')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('birthday', models.DateField(verbose_name='День народження')),
            ],
        ),
    ]
