# Generated by Django 6.0.6 on 2026-06-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_code', models.CharField(max_length=5, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('lyrics', models.TextField()),
            ],
            options={
                'verbose_name': 'Переклад пісні',
                'verbose_name_plural': 'Переклади пісень',
            },
        ),
    ]
