# Generated by Django 6.0.6 on 2026-06-16 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ПІБ')),
                ('slug', models.SlugField(unique=True, verbose_name='Ідентифікатор')),
                ('bio', models.TextField(verbose_name='Біографія')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва теми')),
                ('slug', models.SlugField(unique=True, verbose_name='Ідентифікатор')),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('content', models.TextField(verbose_name='Зміст')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='poems.author', verbose_name='Автор')),
                ('themes', models.ManyToManyField(related_name='poems', to='poems.theme', verbose_name='Тематики')),
            ],
        ),
    ]
